name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: make test
    - name: make example
      run: make example
    - name: run example
      run: example_base && example_sse2 && example_avx && example_avx2 && example_fma && example_fmavx2        

