name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cxxtest
      run: |
          sudo apt-get update
          sudo apt-get install cxxtest
    - name: make
      run: cd test && make
    - name: test
      run: cd test && make test
    - name: make example
      run: cd test && make example
    - name: run example
      run: cd test && example_base && example_sse2 && example_avx && example_avx2 && example_fma && example_fmavx2        

